#!/bin/bash

# Check if exactly two arguments are passed
if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <Yacc file> <Lex file>"
    exit 1
fi

# Assign the Yacc and Lex files to variables
yacc_file="$1"
lex_file="$2"

# Compile the Yacc file
echo "Running yacc -d $yacc_file..."
yacc -d "$yacc_file"
if [ $? -ne 0 ]; then
    echo "Error: Yacc compilation failed."
    exit 1
fi

# Compile the Lex file
echo "Running lex $lex_file..."
lex "$lex_file"
if [ $? -ne 0 ]; then
    echo "Error: Lex compilation failed."
    exit 1
fi

# Compile the C code generated by Lex and Yacc
echo "Running cc lex.yy.c y.tab.c -ll..."
cc lex.yy.c y.tab.c -ll
if [ $? -ne 0 ]; then
    echo "Error: Compilation failed."
    exit 1
fi

# Run the generated executable
echo "Running the executable..."
./a.out << END